name: l4pEnv
channels:
 - conda-forge
 - defaults
envs_dirs:
 - /Users/samarjosyula/Desktop/Projects/llm4pgcc/l4pEnv
dependencies:
 - python=3.10.13
 - pandas
 - rdkit
 - numpy
 - scikit-learn
 - loguru
 - transformers
 - pytorch # CUDA??
 - openai
 - tiktoken
 - tqdm
 - pubchempy
 - pip
 - openpyxl
 - ipykernel
 - tabulate
 - python-dotenv

# ! conda env create -f environment.yml
# ! conda activate pgccEnv
